### ISSUE TITLE
AJAX loading bar across all pages.

### ISSUE THREAD

**Issue by madgen** [ucam-cl-dtg/urop-2013-frontend#13]
When we are partially loading something or navigating to a different page sometimes it is not obvious that the button we clicked is working. 

It would be nice to have a default loading bar across all pages also on Youtube when you switch from one video to another in the same playlist there is a loading bar appearing on top of the page, which i think is really cool. Would be nice if we have something similar.

eg. https://www.youtube.com/watch?v=YYvWpVz770k&list=PLXboAJo1ui6GUpe12EdZVGUKaMpLxmEUn

**Comment by jackdent** [comment]
Done
