### ISSUE TITLE
When doing things on the page w/out refreshing, it slows down over time

### ISSUE THREAD

**Issue by Jocbe** [ucam-cl-dtg/urop-2013-frontend#16]
I assume this is related to more and more javascript building up? I have some significant performance issues, if I stay on the page and do things for a while, without refreshing the page.

**Comment by jackdent** [comment]
Probably due to binding lots of event listeners - investigating now

**Comment by jackdent** [comment]
Lots of Foundation memory leaks. Fixed and submitted pull requests to the Zurb Foundation project.
