### ISSUE TITLE
Top level side bar links should direct to a page of choice.

### ISSUE THREAD

**Issue by madgen** [ucam-cl-dtg/urop-2013-frontend#20]
For example timetable/sugnups link when clicked should expand the side bar and should take you to /signapp/event.

**Comment by hadesgames** [comment]
I think this is a bad idea. Handins doesn't really have a homepage.

**Comment by Jocbe** [comment]
I think this is a bad idea. The categories should only expand on click, nothing else. Imagine being on the website with a 2G connection and having to load an entire page every time you try to expand a menu entry in the sidebar.
