### ISSUE TITLE
Pull in left hand menu from dashboard API

### ISSUE THREAD

**Issue by prc33** [ucam-cl-dtg/urop-2013-frontend#6]
The menu on the left hand side should be populated from an API provided by dashboard - this will allow users to opt-in and -out of services.

To do this, the FrontendServlet will need to read in 2 extra context parameters: the URL at which the dashboard API is available, and an API key for the dashboard (this can be a global permissions API key since it will only be used from the server-side).

**Comment by jackdent** [comment]
API created at the URL "/api/dashboard/settings"

Returns JSON along the lines of

{
    "Dashboard": {
        "Groups": "dashboard/groups",
        "Home": "dashboard",
        "Supervisor Homepage": "dashboard/supervisor",
        "Notifications": "dashboard/notifications",
        "Deadlines": "dashboard/deadlines"
    },
    "Marking Work": {
        "Create bin": "bins/create",
        "Mark answers": "marking",
        "Upload answers": "bins"
    },
    "Timetable/Signups": {
        "Events": "signapp/events",
        "Create new event": "signapp/events/new"
    },
    "Setting Work": {
        "Fairytale land": "fairytale",
        "Browse own content": "users/me",
        "Browse questions": "q/search",
        "Create question set": "sets/add",
        "Browse question sets": "sets"
    }
}

**Comment by jackdent** [comment]
JSON modified to include icons
